version: "3.3"
services:
  db:
    container_name: postgraphile-docker-db
    restart: always
    image: postgraphile-docker-db
    build:
      context: ./db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - network
    ports:
      - 5432:5432

  graphql:
    container_name: postgraphile-docker-graphql
    restart: always
    image: postgraphile-docker-graphql
    build:
      context: ./graphql
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - network
    ports:
      - 5433:5433
    command:
      [
        "--connection",
        "${DATABASE_URL}",
        "--port",
        "5433",
        "--schema",
        "public",
        "--append-plugins",
        "postgraphile-plugin-connection-filter"
      ]

networks:
  network:

volumes:
  db:
